import { Response } from "express";
import { AuthRequest } from "../middlewares/authMiddleware";

type Urgency = "low" | "medium" | "high" | "emergency";
type ChatRole = "user" | "assistant";
interface ChatMessage {
    role: ChatRole;
    content: string;
}

interface Conclusion {
    specialization: string;
    urgency: Urgency;
    reasoning: string;
}

type AgentTurn =
    | { done: false; question: string; quickReplies?: string[] }
    | ({ done: true } & Conclusion);

const SPECIALIZATIONS = [
    "General Physician",
    "Cardiology",
    "Dermatology",
    "Orthopedics",
    "Pediatrics",
    "ENT",
    "Neurology",
    "Psychiatry",
    "Gynecology",
    "Ophthalmology",
    "Dentistry",
    "Pulmonology",
    "Gastroenterology",
    "Endocrinology",
    "Urology",
];

const DISCLAIMER =
    "This is an automated suggestion based on the symptoms you described, not a medical diagnosis. " +
    "If this could be a medical emergency, call your local emergency number immediately.";

// Deterministic, curated guidance — not generated by the AI model, even
// when OpenAI is configured. Genuinely useful on its own, independent of
// whether the doctor list below it has anyone real and bookable in it.
const SELF_CARE_GUIDANCE: Record<Urgency, string> = {
    low: "Most cases like this improve on their own with rest, fluids, and over-the-counter relief as needed. If it hasn't improved in a few days, or it gets worse, that's the point to get it looked at.",
    medium: "Worth getting checked in the next few days rather than waiting it out. In the meantime, rest and keep an eye on it — new symptoms, fever, or worsening pain mean it's time to move sooner.",
    high: "Worth seeing a doctor within the next 24 hours rather than scheduling something routine. Avoid strenuous activity in the meantime, and seek emergency care immediately if it gets noticeably worse.",
    emergency: "This needs emergency care now, not a scheduled appointment.",
};

const EMERGENCY_KEYWORDS = [
    "can't breathe", "cannot breathe", "difficulty breathing", "chest pain", "unconscious",
    "severe bleeding", "bleeding heavily", "stroke", "heart attack", "seizure", "not breathing",
    "suicidal", "poisoning", "severe allergic",
];

const RULES: { keywords: string[]; specialization: string; urgency: Urgency }[] = [
    { keywords: ["chest pain", "heart", "palpitation", "blood pressure"], specialization: "Cardiology", urgency: "high" },
    { keywords: ["skin", "rash", "acne", "itch", "mole"], specialization: "Dermatology", urgency: "low" },
    { keywords: ["bone", "fracture", "joint", "back pain", "sprain", "knee", "shoulder"], specialization: "Orthopedics", urgency: "medium" },
    { keywords: ["child", "infant", "baby", "toddler"], specialization: "Pediatrics", urgency: "medium" },
    { keywords: ["ear", "nose", "throat", "sinus", "hearing"], specialization: "ENT", urgency: "low" },
    { keywords: ["headache", "migraine", "dizziness", "numbness", "seizure", "memory"], specialization: "Neurology", urgency: "medium" },
    { keywords: ["anxiety", "depress", "stress", "sleep", "mood", "panic"], specialization: "Psychiatry", urgency: "low" },
    { keywords: ["pregnan", "period", "menstrual", "gynec"], specialization: "Gynecology", urgency: "medium" },
    { keywords: ["eye", "vision", "blurry"], specialization: "Ophthalmology", urgency: "low" },
    { keywords: ["tooth", "teeth", "gum", "dental"], specialization: "Dentistry", urgency: "low" },
    { keywords: ["cough", "breath", "asthma", "wheeze", "lung"], specialization: "Pulmonology", urgency: "medium" },
    { keywords: ["stomach", "abdominal", "nausea", "vomit", "diarrhea", "digestion"], specialization: "Gastroenterology", urgency: "medium" },
    { keywords: ["thyroid", "diabetes", "sugar level", "hormone"], specialization: "Endocrinology", urgency: "medium" },
    { keywords: ["urinary", "kidney", "bladder"], specialization: "Urology", urgency: "medium" },
];

function baseMatch(symptoms: string): { specialization: string; urgency: Urgency } {
    const text = symptoms.toLowerCase();
    for (const rule of RULES) {
        if (rule.keywords.some((k) => text.includes(k))) {
            return { specialization: rule.specialization, urgency: rule.urgency };
        }
    }
    return { specialization: "General Physician", urgency: "low" };
}

function escalate(urgency: Urgency): Urgency {
    if (urgency === "low") return "medium";
    if (urgency === "medium") return "high";
    return urgency;
}

function isEmergencyText(text: string): boolean {
    const t = text.toLowerCase();
    return EMERGENCY_KEYWORDS.some((k) => t.includes(k));
}

const MAX_QUESTIONS = 3;

/**
 * No-AI fallback. Genuinely adaptive (question is chosen from the
 * patient's initial symptom category, not a fixed universal script), but
 * bounded to one tailored follow-up — true per-answer dynamism needs the
 * OpenAI path below.
 */
const CATEGORY_FOLLOWUPS: Record<string, { question: string; quickReplies: string[]; escalateIf: string[] }> = {
    Cardiology: {
        question: "Do you also feel short of breath, dizzy, or sweaty along with it?",
        quickReplies: ["Yes", "No"],
        escalateIf: ["yes"],
    },
    Dermatology: {
        question: "Is the area spreading, or is there any pain, oozing, or fever with it?",
        quickReplies: ["Yes, one of those", "No, just the skin issue"],
        escalateIf: ["yes"],
    },
    Orthopedics: {
        question: "Can you still move or put weight on it normally?",
        quickReplies: ["Yes, mostly normal", "No, it's difficult"],
        escalateIf: ["no"],
    },
    Pediatrics: {
        question: "Are they eating, drinking, and behaving normally otherwise?",
        quickReplies: ["Yes, mostly normal", "No, clearly not themselves"],
        escalateIf: ["no"],
    },
    ENT: {
        question: "Is it affecting your breathing or hearing, or mainly just discomfort?",
        quickReplies: ["Just discomfort", "Affecting breathing/hearing"],
        escalateIf: ["affecting"],
    },
    Neurology: {
        question: "Is this the worst episode you've ever had, or any weakness/confusion with it?",
        quickReplies: ["No, fairly typical", "Yes, worse or with other symptoms"],
        escalateIf: ["yes"],
    },
    Psychiatry: {
        question: "Is this affecting your ability to function day-to-day?",
        quickReplies: ["Not really", "Somewhat", "Yes, significantly"],
        escalateIf: ["significantly"],
    },
    Gynecology: {
        question: "Is there any severe pain or unusual bleeding along with it?",
        quickReplies: ["Yes", "No"],
        escalateIf: ["yes"],
    },
    Ophthalmology: {
        question: "Any sudden vision loss or eye pain along with it?",
        quickReplies: ["Yes", "No"],
        escalateIf: ["yes"],
    },
    Dentistry: {
        question: "Is there any facial swelling or fever along with it?",
        quickReplies: ["Yes", "No"],
        escalateIf: ["yes"],
    },
    Pulmonology: {
        question: "Are you having any difficulty breathing, even mild, along with it?",
        quickReplies: ["Yes", "No"],
        escalateIf: ["yes"],
    },
    Gastroenterology: {
        question: "Any blood, or is it getting noticeably worse?",
        quickReplies: ["Yes", "No"],
        escalateIf: ["yes"],
    },
    Endocrinology: {
        question: "Has this been going on for more than a couple of weeks?",
        quickReplies: ["Yes", "No, fairly recent"],
        escalateIf: ["yes"],
    },
    Urology: {
        question: "Any fever or significant pain along with it?",
        quickReplies: ["Yes", "No"],
        escalateIf: ["yes"],
    },
    "General Physician": {
        question: "On a scale of mild to severe, how would you describe it, and has it lasted more than a few days?",
        quickReplies: ["Mild, recent", "Moderate/severe, or lasting a while"],
        escalateIf: ["moderate", "severe", "while"],
    },
};

function fallbackAgentTurn(messages: ChatMessage[]): AgentTurn {
    const firstUserMessage = messages.find((m) => m.role === "user")?.content || "";
    const assistantTurns = messages.filter((m) => m.role === "assistant").length;

    if (isEmergencyText(firstUserMessage)) {
        return {
            done: true,
            specialization: "General Physician",
            urgency: "emergency",
            reasoning: "What you described could be serious and shouldn't wait for a routine appointment.",
        };
    }

    const base = baseMatch(firstUserMessage);

    if (assistantTurns === 0) {
        const followup = CATEGORY_FOLLOWUPS[base.specialization];
        return { done: false, question: followup.question, quickReplies: followup.quickReplies };
    }

    const lastAnswer = (messages[messages.length - 1]?.content || "").toLowerCase();
    const followup = CATEGORY_FOLLOWUPS[base.specialization];
    let urgency = base.urgency;
    if (followup.escalateIf.some((trigger) => lastAnswer.includes(trigger))) {
        urgency = escalate(urgency);
    }

    return {
        done: true,
        specialization: base.specialization,
        urgency,
        reasoning: `Based on what you described, a ${base.specialization} specialist is a reasonable starting point.`,
    };
}

async function openAiAgentTurn(messages: ChatMessage[]): Promise<AgentTurn | null> {
    const apiKey = process.env["OPENAI_API_KEY"];
    if (!apiKey) return null;

    const assistantTurns = messages.filter((m) => m.role === "assistant").length;
    const mustConclude = assistantTurns >= MAX_QUESTIONS;

    const systemPrompt =
        "You are a triage assistant embedded in a healthcare app, having a short conversation with a patient " +
        "to work out how urgently they need care and which kind of specialist to see.\n\n" +
        "Rules:\n" +
        "- Ask ONE short, specific follow-up question at a time, directly informed by everything the patient " +
        "has said so far. Never repeat a question you've effectively already asked.\n" +
        `- You may ask at most ${MAX_QUESTIONS} follow-up questions before you must conclude. Fewer is fine if ` +
        "you're confident sooner.\n" +
        "- When a question naturally has a short set of likely answers (yes/no, a scale, a small list), include " +
        "2-4 short quickReplies strings. Use null for genuinely open-ended questions.\n" +
        "- If anything described could be a medical emergency (e.g. chest pain with shortness of breath, stroke " +
        "symptoms, severe bleeding, suicidal ideation, difficulty breathing), stop immediately and conclude with " +
        "urgency \"emergency\" — do not ask further questions.\n" +
        "- Never diagnose or give medication/dosing advice — only ever a specialization and urgency with one " +
        "short, plain-language reason.\n" +
        `- specialization must be exactly one of: ${SPECIALIZATIONS.join(", ")}.\n` +
        (mustConclude ? "- You have already asked the maximum number of questions. You MUST conclude now (done:true) using your best judgement from the conversation so far.\n" : "") +
        "\nRespond with ONLY raw JSON, no markdown fences, matching exactly one of these shapes:\n" +
        'Still gathering info: {"done": false, "question": "string", "quickReplies": ["string", ...] | null}\n' +
        'Ready to conclude: {"done": true, "specialization": "string", "urgency": "low"|"medium"|"high"|"emergency", "reasoning": "string"}';

    try {
        const response = await fetch("https://api.openai.com/v1/chat/completions", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${apiKey}`,
            },
            body: JSON.stringify({
                model: "gpt-4o-mini",
                temperature: 0.3,
                response_format: { type: "json_object" },
                messages: [
                    { role: "system", content: systemPrompt },
                    ...messages.map((m) => ({ role: m.role, content: m.content })),
                ],
            }),
        });

        if (!response.ok) return null;

        const data: any = await response.json();
        const content = data?.choices?.[0]?.message?.content;
        if (!content) return null;

        const parsed = JSON.parse(content);

        if (parsed.done) {
            if (!SPECIALIZATIONS.includes(parsed.specialization)) parsed.specialization = "General Physician";
            if (!["low", "medium", "high", "emergency"].includes(parsed.urgency)) parsed.urgency = "medium";
            return {
                done: true,
                specialization: parsed.specialization,
                urgency: parsed.urgency,
                reasoning: String(parsed.reasoning || "").slice(0, 300),
            };
        }

        if (mustConclude) return null; // model didn't comply with the hard cap — fall through to safety net
        return {
            done: false,
            question: String(parsed.question || "").slice(0, 300),
            quickReplies: Array.isArray(parsed.quickReplies) ? parsed.quickReplies.slice(0, 4).map(String) : undefined,
        };
    } catch {
        return null;
    }
}

function sanitizeMessages(raw: unknown): ChatMessage[] {
    if (!Array.isArray(raw)) return [];
    return raw
        .filter((m): m is ChatMessage => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string")
        .map((m) => ({ role: m.role, content: m.content.slice(0, 500) }))
        .slice(-20);
}

export const symptomChat = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const messages = sanitizeMessages(req.body?.messages);

        if (messages.length === 0 || messages[0].role !== "user" || !messages[0].content.trim()) {
            res.status(400).json({ msg: "Please describe your symptoms to start." });
            return;
        }
        const assistantTurns = messages.filter((m) => m.role === "assistant").length;
        if (assistantTurns > MAX_QUESTIONS) {
            res.status(400).json({ msg: "Conversation too long." });
            return;
        }

        const aiResult = await openAiAgentTurn(messages);
        const turn: AgentTurn = aiResult || fallbackAgentTurn(messages);
        const mode = aiResult ? "ai" : "fallback";

        if (!turn.done) {
            res.json({ done: false, mode, question: turn.question, quickReplies: turn.quickReplies });
            return;
        }

        res.json({
            done: true,
            mode,
            specialization: turn.specialization,
            urgency: turn.urgency,
            reasoning: turn.reasoning,
            selfCare: turn.urgency === "emergency" ? SELF_CARE_GUIDANCE.emergency : SELF_CARE_GUIDANCE[turn.urgency],
            disclaimer: DISCLAIMER,
        });
    } catch (err: any) {
        res.status(500).json({ msg: "Server error", error: err.message });
    }
};
