import { Response } from "express";
import { AuthRequest } from "../middlewares/authMiddleware";
import { DoctorProfile } from "../models/DoctorProfile";
import { User } from "../models/User";

// Real-world specialization naming is inconsistent (e.g. doctors listed as
// "General Medicine" rather than "General Physician"), so a few common
// synonyms are matched alongside the canonical name.
const SPECIALIZATION_ALIASES: Record<string, string[]> = {
    "General Physician": ["General Medicine", "Family Medicine", "General Practice"],
};

function specializationRegex(specialization: string): RegExp {
    const terms = [specialization, ...(SPECIALIZATION_ALIASES[specialization] || [])];
    return new RegExp(terms.join("|"), "i");
}

type Urgency = "low" | "medium" | "high" | "emergency";
type Duration = "today" | "few-days" | "over-week";
type Severity = "mild" | "moderate" | "severe";

interface TriageInput {
    symptoms: string;
    duration: Duration;
    severity: Severity;
    redFlags: string[];
}

interface Triage {
    specialization: string;
    urgency: Urgency;
    reasoning: string;
}

const SPECIALIZATIONS = [
    "General Physician",
    "Cardiology",
    "Dermatology",
    "Orthopedics",
    "Pediatrics",
    "ENT",
    "Neurology",
    "Psychiatry",
    "Gynecology",
    "Ophthalmology",
    "Dentistry",
    "Pulmonology",
    "Gastroenterology",
    "Endocrinology",
    "Urology",
];

const DISCLAIMER =
    "This is an automated suggestion based on the symptoms you described, not a medical diagnosis. " +
    "If this could be a medical emergency, call your local emergency number immediately.";

// Deterministic, curated guidance — not generated by the AI model, even
// when OpenAI is configured. Genuinely useful on its own, independent of
// whether the doctor list below it has anyone real and bookable in it.
const SELF_CARE_GUIDANCE: Record<Urgency, string> = {
    low: "Most cases like this improve on their own with rest, fluids, and over-the-counter relief as needed. If it hasn't improved in a few days, or it gets worse, that's the point to get it looked at.",
    medium: "Worth getting checked in the next few days rather than waiting it out. In the meantime, rest and keep an eye on it — new symptoms, fever, or worsening pain mean it's time to move sooner.",
    high: "Worth seeing a doctor within the next 24 hours rather than scheduling something routine. Avoid strenuous activity in the meantime, and seek emergency care immediately if it gets noticeably worse.",
    emergency: "This needs emergency care now, not a scheduled appointment.",
};

const EMERGENCY_KEYWORDS = [
    "can't breathe", "cannot breathe", "difficulty breathing", "chest pain", "unconscious",
    "severe bleeding", "bleeding heavily", "stroke", "heart attack", "seizure", "not breathing",
    "suicidal", "poisoning", "severe allergic",
];

const RULES: { keywords: string[]; specialization: string; urgency: Urgency }[] = [
    { keywords: ["chest pain", "heart", "palpitation", "blood pressure"], specialization: "Cardiology", urgency: "high" },
    { keywords: ["skin", "rash", "acne", "itch", "mole"], specialization: "Dermatology", urgency: "low" },
    { keywords: ["bone", "fracture", "joint", "back pain", "sprain", "knee", "shoulder"], specialization: "Orthopedics", urgency: "medium" },
    { keywords: ["child", "infant", "baby", "toddler"], specialization: "Pediatrics", urgency: "medium" },
    { keywords: ["ear", "nose", "throat", "sinus", "hearing"], specialization: "ENT", urgency: "low" },
    { keywords: ["headache", "migraine", "dizziness", "numbness", "seizure", "memory"], specialization: "Neurology", urgency: "medium" },
    { keywords: ["anxiety", "depress", "stress", "sleep", "mood", "panic"], specialization: "Psychiatry", urgency: "low" },
    { keywords: ["pregnan", "period", "menstrual", "gynec"], specialization: "Gynecology", urgency: "medium" },
    { keywords: ["eye", "vision", "blurry"], specialization: "Ophthalmology", urgency: "low" },
    { keywords: ["tooth", "teeth", "gum", "dental"], specialization: "Dentistry", urgency: "low" },
    { keywords: ["cough", "breath", "asthma", "wheeze", "lung"], specialization: "Pulmonology", urgency: "medium" },
    { keywords: ["stomach", "abdominal", "nausea", "vomit", "diarrhea", "digestion"], specialization: "Gastroenterology", urgency: "medium" },
    { keywords: ["thyroid", "diabetes", "sugar level", "hormone"], specialization: "Endocrinology", urgency: "medium" },
    { keywords: ["urinary", "kidney", "bladder"], specialization: "Urology", urgency: "medium" },
];

function baseMatch(symptoms: string): { specialization: string; urgency: Urgency } {
    const text = symptoms.toLowerCase();
    for (const rule of RULES) {
        if (rule.keywords.some((k) => text.includes(k))) {
            return { specialization: rule.specialization, urgency: rule.urgency };
        }
    }
    return { specialization: "General Physician", urgency: "low" };
}

function escalate(urgency: Urgency): Urgency {
    if (urgency === "low") return "medium";
    if (urgency === "medium") return "high";
    return urgency;
}

function ruleBasedTriage(input: TriageInput): Triage {
    const { symptoms, duration, severity, redFlags } = input;

    if (EMERGENCY_KEYWORDS.some((k) => symptoms.toLowerCase().includes(k))) {
        return {
            specialization: "General Physician",
            urgency: "emergency",
            reasoning: "What you described could be serious and shouldn't wait for a routine appointment.",
        };
    }

    const base = baseMatch(symptoms);
    let urgency = base.urgency;
    const notes: string[] = [];

    if (redFlags.length > 0 && severity === "severe") {
        urgency = "emergency";
    } else {
        if (redFlags.length > 0) {
            urgency = escalate(urgency);
            notes.push(`the additional symptoms you flagged (${redFlags.join(", ").toLowerCase()}) are worth having a doctor check on soon`);
        }
        if (severity === "severe") {
            urgency = escalate(urgency);
            notes.push("given how severe you rated this, it's worth getting seen sooner rather than later");
        }
        if (duration === "over-week" && notes.length === 0 && urgency === "low") {
            urgency = "medium";
            notes.push("since this has lasted over a week, it's a good idea not to wait much longer");
        }
    }

    if (urgency === "emergency") {
        return {
            specialization: "General Physician",
            urgency: "emergency",
            reasoning: "The combination of severity and symptoms you described could be serious and should be looked at right away.",
        };
    }

    const reasoning = notes.length > 0
        ? `Based on what you described, a ${base.specialization} specialist is a reasonable starting point — ${notes.join(", and ")}.`
        : `Based on the symptoms you described, a ${base.specialization} specialist is a reasonable starting point.`;

    return { specialization: base.specialization, urgency, reasoning };
}

async function openAiTriage(input: TriageInput): Promise<Triage | null> {
    const apiKey = process.env["OPENAI_API_KEY"];
    if (!apiKey) return null;

    try {
        const userContent =
            `Symptoms: ${input.symptoms}\n` +
            `Duration: ${input.duration}\n` +
            `Self-rated severity: ${input.severity}\n` +
            `Additional symptoms present: ${input.redFlags.length ? input.redFlags.join(", ") : "none reported"}`;

        const response = await fetch("https://api.openai.com/v1/chat/completions", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${apiKey}`,
            },
            body: JSON.stringify({
                model: "gpt-4o-mini",
                temperature: 0.2,
                response_format: { type: "json_object" },
                messages: [
                    {
                        role: "system",
                        content:
                            "You are a triage assistant for a healthcare app. Given a patient's plain-language " +
                            "description of their symptoms plus follow-up answers on duration, self-rated severity, " +
                            "and additional (red-flag) symptoms, respond with ONLY a JSON object with keys: " +
                            `"specialization" (must be exactly one of: ${SPECIALIZATIONS.join(", ")}), ` +
                            '"urgency" (one of: low, medium, high, emergency), and "reasoning" (one short sentence, ' +
                            "plain language, no diagnosis, no medication advice, referencing the follow-up answers " +
                            "where relevant). Weigh severe self-rated severity and additional symptoms heavily toward " +
                            "higher urgency. Use \"emergency\" only for symptoms that suggest a life-threatening condition.",
                    },
                    { role: "user", content: userContent },
                ],
            }),
        });

        if (!response.ok) return null;

        const data: any = await response.json();
        const content = data?.choices?.[0]?.message?.content;
        if (!content) return null;

        const parsed = JSON.parse(content);
        if (!SPECIALIZATIONS.includes(parsed.specialization)) {
            parsed.specialization = "General Physician";
        }
        if (!["low", "medium", "high", "emergency"].includes(parsed.urgency)) {
            parsed.urgency = "medium";
        }
        return {
            specialization: parsed.specialization,
            urgency: parsed.urgency,
            reasoning: String(parsed.reasoning || "").slice(0, 300),
        };
    } catch {
        return null;
    }
}

const VALID_DURATIONS: Duration[] = ["today", "few-days", "over-week"];
const VALID_SEVERITIES: Severity[] = ["mild", "moderate", "severe"];

export const symptomCheck = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const symptoms = String(req.body?.symptoms || "").trim();
        const duration: Duration = VALID_DURATIONS.includes(req.body?.duration) ? req.body.duration : "today";
        const severity: Severity = VALID_SEVERITIES.includes(req.body?.severity) ? req.body.severity : "moderate";
        const redFlags: string[] = Array.isArray(req.body?.redFlags)
            ? req.body.redFlags.filter((f: unknown) => typeof f === "string").slice(0, 10)
            : [];

        if (!symptoms) {
            res.status(400).json({ msg: "Please describe your symptoms." });
            return;
        }
        if (symptoms.length > 1000) {
            res.status(400).json({ msg: "Please keep your description under 1000 characters." });
            return;
        }

        const input: TriageInput = { symptoms, duration, severity, redFlags };
        const triage = (await openAiTriage(input)) || ruleBasedTriage(input);

        // Emergency cases shouldn't be routed into routine appointment booking.
        if (triage.urgency === "emergency") {
            res.json({
                specialization: triage.specialization,
                urgency: triage.urgency,
                reasoning: triage.reasoning,
                selfCare: SELF_CARE_GUIDANCE.emergency,
                disclaimer: DISCLAIMER,
                doctors: [],
            });
            return;
        }

        const regex = specializationRegex(triage.specialization);

        let doctors = await DoctorProfile.find({ specialization: { $regex: regex } })
            .populate("user", "name email")
            .sort({ experience: -1 })
            .limit(3);

        let doctorList = doctors.map((d) => ({
            id: d._id,
            name: (d.user as any)?.name || "Unknown",
            specialization: d.specialization,
            experience: d.experience,
        }));

        // Fall back to Users with a Doctor role when no DoctorProfile records exist yet.
        if (doctorList.length === 0) {
            const fallbackDoctors = await User.find({ role: "Doctor", specialization: { $regex: regex } })
                .select("name specialization")
                .limit(3);
            doctorList = fallbackDoctors.map((d) => ({
                id: d._id,
                name: d.name,
                specialization: d.specialization || triage.specialization,
                experience: 0,
            }));
        }

        res.json({
            specialization: triage.specialization,
            urgency: triage.urgency,
            reasoning: triage.reasoning,
            selfCare: SELF_CARE_GUIDANCE[triage.urgency],
            disclaimer: DISCLAIMER,
            doctors: doctorList,
            doctorsNote: "These are demo doctor accounts seeded for this project, not a real hospital network — use \"Find real care near you\" for actual nearby clinics.",
        });
    } catch (err: any) {
        res.status(500).json({ msg: "Server error", error: err.message });
    }
};
